apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: keda-demo
type: Opaque
stringData:
  host: amqp://guest:guest@rabbitmq.keda-demo.svc.cluster.local:5672/
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: keda-demo
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbit-worker-queue
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: rabbit-worker
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 30
  triggers:
    - type: rabbitmq
      metadata:
        queueName: recap-jobs
        mode: QueueLength
        value: "5"
      authenticationRef:
        name: rabbitmq-trigger-auth
