apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-redis-queue-20
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: worker
  minReplicaCount: 0
  maxReplicaCount: 6
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
    - type: redis
      metadata:
        address: redis.keda-demo.svc.cluster.local:6379
        listName: highlight-jobs
        listLength: "20"
